#!/bin/bash

# quiet?
[[ $1 == -q ]] && {
  quiet=1; shift
} || quiet=0

# if single file, and exists return 0 / not exists return 1
[[ $# == 1 ]] && {
  [[ -s "$1" ]] && exit 0 || exit 1
}

# otherwise

exists=""
for file in $@; do
  if [[ ! -s "$file" ]]; then
    (( $quiet )) || echo "File $file does not exist." >&2
    error=1
  else
    exists="$exists $file"
  fi
done

if (( $error )); then
  [[ -z ${exists// /} ]] && exit 2 || (echo $exists; exit 1)
else
  echo $exists
  exit 0
fi
