#!/bin/bash

if [[ $# -lt 2 ]]; then
  echo "Usage: xyz program [arguments]"
  exit -1
fi

export SCRIPT_DIR=$(dirname $0)

program=${SCRIPT_DIR}/xyz_$1

if [[ ! -f $program ]]; then
  echo "xyz $1 not found."
  exit -1
fi

${program} "${@:2}"

