#!/bin/bash

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "Usage: xyz minmax file"
  exit 1
fi

set -e
$SCRIPTDIR/check_files -q $1

nat=$($SCRIPTDIR/xyz_nat "$1")

[[ "$1" == *.lammpstrj ]] && header=9 || header=2

awk -vnat=$nat -vh=$header '
  NR==h+1{for(i=2; i<5; i++){ min[i-2]=$i; max[i-2]=$i}}
  NR>h+1&&NR<nat+h+1{
    for(i=2; i<5; i++) {
      if ( $i < min[i-2] ) min[i-2] = $i
      if ( $i > max[i-2] ) max[i-2] = $i
    }
  }
  NR==nat+h+1 {
    for(i=0; i<3; i++) {
      printf "%15.10f %15.10f\n", min[i], max[i]
    }
    exit
  } ' "$1"
