#!/bin/bash

if [[ $# -ne 1 || "$1" == -h ]]; then
  echo "Usage: xyz average [file]"
  echo "Calculate the average positions"
  exit 1
fi

set -e
$SCRIPTDIR/check_files "$1"

nat=$($SCRIPTDIR/xyz_nat "$1")

[[ "$1" == *.lammpstrj ]] && header=9 || header=2

$SCRIPTDIR/xyz_header $1

awk -vskip=$header -vnat=$nat '
     NR==skip{i=0; nf++}
     NR>skip{el[i]=$1;
     for(j=2; j<=NF; j++)
       data[i][j] += $j
      i++
    }
    END{
      for(i=0;i<nat;i++) {
        printf "%-3s ", el[i]
        for(j=2; j<=NF; j++)
          printf "%15.9f ", data[i][j]/nf
        printf "\n"
      }
    }' $1
