#!/bin/bash
if [[ $# -lt 1 ]]; then
  echo "Usage: xyz rmsd [-f] file1 [file2]"
  echo "-f force = continue even if some files are not found"
  exit -1
fi

if [[ $1 == "-f" ]]; then
  force=1
  shift
fi

files="$@"

if [[ $force -ne 1 ]]; then
  set -e
fi

files=( $($SCRIPT_DIR/check_files $files) )

if [[ ${#files[@]} == 1 ]]; then
  awk -vnat=$(head -1 ${files[0]}) 'BEGIN {
    sum = 0
    for ( i=0; i<2; i++ ) {
      getline
    }
    for ( i=0; i<nat; i++ ) {
      getline
      for ( j=0; j<3; j++ ) {
        coor[i][j] = $(j+2)
      }
    }
  }
  {
    i = ((NR-1)%(nat+2)-2)
    if (i >= 0) {
      for ( j=0; j<3; j++ ) {
        sum += (coor[i][j] - $(j+2))**2
        coor[i][j] = $(j+2)
      }
      if (i == nat-1) {
        print sqrt(sum/nat)
        sum = 0
      }
    }
  }' ${files[0]}
elif [[ ${#files[@]} -gt 2 ]]; then
  echo "RMSD of ${#files[@]} files is not implemented."
  exit -1
else
  if [[ $(wc -l < ${files[0]}) -ne $(wc -l < ${files[1]}) ]]; then
    echo "${files[0]} and ${files[1]} should have same number of atoms/lines."
  fi
  paste ${files[@]} | awk 'NR>2{sum+=($2-$6)**2+($3-$7)**2+($4-$8)**2; i++}END{print sqrt(sum/i)}'
fi
exit 0
