#!/bin/bash

if [[ $# -ne 4 ]]; then
  echo "Usage: xyz shift file x y z"
  exit 1
fi

set -e

$SCRIPTDIR/check_files "$1"
$SCRIPTDIR/check_float  $2
$SCRIPTDIR/check_float  $3
$SCRIPTDIR/check_float  $4

nat=$($SCRIPTDIR/xyz_nat "$1")
[[ "$1" == *.lammpstrj ]] && header=9 || header=2

awk -vh=$header -vnat=$nat -vx=$2 -vy=$3 -vz=$4 '{
  l = (NR-1)%(nat+h)
  if ( l < h ) {
    print
  } else {
    printf "%-3s %15.9f %15.9f %15.9f\n", $1, $2+x, $3+y, $4+z
  }
}' "$1"
