#!/bin/bash

if [[ $# -ne 1 || "$1" == -h ]]; then
  echo "Usage: xyz com [file]"
  echo "Returns center of not-really-the-mass of a single frame"
  echo "If no file given, will read the stdin"
  exit 1
fi

set -e
$SCRIPTDIR/check_files "$1"

nat=$($SCRIPTDIR/xyz_nat "$1")

[[ "$1" == *.lammpstrj ]] && header=9 || header=2

awk -vskip=$header -vnat=$nat '
     NR>skip{x+=$2; y+=$3; z+=$4}
     END{printf "%10.6f %10.6f %10.6f\n", x/nat, y/nat, z/nat}' $1
