#!/bin/bash

if [[ $# -ne 1 || "$1" == -h ]]; then
  echo "Usage: xyz header [file]"
  echo "Returns header of a single frame"
  echo "file should be given if data not read from stdin"
  exit 1
fi

set -e
$SCRIPTDIR/check_files "$1"

[[ "$1" == *.lammpstrj ]] && header=9 || header=2

awk "NR<$header+1" "$1"
