#!/bin/bash

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "Usage: xyz minmax file [dir] "
  echo "dir = 1 for x, 2 for y, 3 for z"
  exit -1
fi

set -e
$SCRIPT_DIR/check_files -q $1

if [[ $# -eq 2 ]]; then
  awk -vdir=$2 \
    'NR==3 { min = $(dir+1); max = $(dir+1) }
     NR>3  { if      ( min > $(dir+1) ) min = $(dir+1)
             else if ( max < $(dir+1) ) max = $(dir+1)
     }
     END   { printf "%13.6f %13.6f\n", min, max }
     ' $1
else
  awk 'NR==3 { min[1] = $2; min[2] = $3; min[3] = $4
               max[1] = $2; max[2] = $3; max[3] = $4 }
       NR>3  {
         for(i=1; i<4; i++) {
           if ( min[i] > $(i+1) )
             min[i] = $(i+1)
           else if ( max[i] < $(i+1) )
             max[i] = $(i+1)
         }
       }
       END {
         split("x y z", letter)
         for(i=1; i<4; i++) {
           printf "%13.6f ≤ %s ≤ %13.6f\n", min[i], letter[i], max[i]
         }
       } ' $1
fi

