#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "Usage: xyz com file"
  exit -1
fi

set -e
$SCRIPT_DIR/check_files -q $1

awk 'NR>2{nat++; x+=$2; y+=$3; z+=$4}
     END{printf "%10.6f %10.6f %10.6f\n", x/nat, y/nat, z/nat}' $1
