#!/bin/bash
if [[ $# -lt 1 ]]; then
  echo "Usage: xyz rmsd file1 [file2]"
  echo "If a single file given, prints the RMSD of all frames relative to first"
  echo "If two files are given, prints the RMSD of each frame in the second file"
  echo "wrt to the corresponding frame in the first file"
  exit 1
fi

files="$@"

files=( $($SCRIPTDIR/check_files $files) )

if   [[ ${@files[@]} -eq 1 ]]; then
  nat=$($SCRIPTDIR/xyz_nat ${files[0]})
  [[ "${files[0]}" == *.lammpstrj ]] && header=9 || header=2
  awk -vnat=$(nat) -vskip=$header '
    BEGIN {
      sum = 0
      # skip header
      for ( i = 0; i < skip; i++ ) getline;
      # store coordinates of the first frame
      for ( i = 0; i <  nat; i++ ) {
        getline
        for ( j = 0; j < 3; j++ ) {
          coor[i][j] = $(j+2)
        }
      }
    }
    {
      atom = ( (NR-1) % (nat+skip) - skip ) # atom index

      if ( atom >= 0 ) {
        for ( j = 0; j < 3; j++ ) {
          sum += (coor[i][j] - $(j+2))**2
#         coor[i][j] = $(j+2)
        }
      }

      if ( atom == nat-1) {
        print sqrt(sum/nat)
        sum = 0
      }
    }' ${files[0]}
elif [[ ${@files[@]} -eq 2 ]]; then
  nat=$($SCRIPTDIR/xyz_nat ${files[0]})

  if [[ $nat -ne $($SCRIPTDIR/xyz_nat ${files[1]}) ]]; then
    echo "The files should have same number of atoms."
    exit 1
  fi

  if [[ ${files[0]##*.} -ne ${files[1]##*.} ]]; then
    echo "The files should have same format."
    exit 1
  fi

  [[ "${files[0]}" == *.lammpstrj ]] && header1=9 || header2=2

  paste ${files[@]}|awk -vn=$nat -vskip=$header '{
    atom = ( (NR-1) % (nat+skip) - skip ) # atom index
      if (atom == -1) {
        rmsd = 0
      } else if (atoms > -1) {
        rmsd += ($2-$6)**2 + ($3-$7)**2 + ($4-$8)**2
      }
      if (atom == nat-1)  {
        print sqrt(rmsd/nat)
      }
  }'
else
  echo "RMSD of ${#files[@]} files is not implemented."
  exit 1
fi

exit 0
