#!/bin/bash

if [[ $# -lt 1 ]]; then
  echo "Usage: xyz merge [-f] file1 [file2 [file3 ...]]"
  echo "-f force = continue even if some files are not found"
  exit 1
fi

[[ $1 == -f ]] && shift || set -e

files=($($SCRIPTDIR/check_files $@))

newnat=0

for file in ${files[@]}; do
  newnat=$((newnat+$($SCRIPTDIR/xyz_nat $file)))
done


[[ "$1" == *.lammpstrj ]] && natline=4 || natline=1

sed "${natline}c${newnat}" "${files[0]}"

for file in ${files[@]:1}; do
  $SCRIPTDIR/xyz_coor "$file"
done
