#!/bin/bash

# slow?
[[ $1 == -s ]] && {
  slow=1; shift
} || slow=0


if [[ $# -lt 1 || $# -gt 2 || $1 == -h ]]; then
  echo "Usage: xyz last [-s] file [num]"
  echo "Use the slower, but more robust version."
  exit 1
fi

set -e
$SCRIPTDIR/check_files -q $1


if (( $slow )); then

  # get n, m: first, last frame of interest
  m=$($SCRIPTDIR/xyz_nframes "$1")
  n=$((m-${2:-1}+1))

  [[ $n -lt 1 ]] && n=1 && echo "Not all frames exist" >&2

  $SCRIPTDIR/xyz_slice "$1" $n $m
else
  if [[ $1 == *.lammpstrj ]]; then
    tac $1 | awk -vn=${2:-1} '{print}/TIMESTEP/{counter++}n==counter{exit}'|tac
  else
    tac $1 | awk '-vn{print, last=NF}NF==1&&last!=1{counter++}n==counter{exit}' | tac
  fi
fi
